# Generated by Django 5.2.17 on 2026-09-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergarten',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kindergarten/background/', verbose_name='Фоновое фото'),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='hero_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kindergarten/hero/', verbose_name='Главное фото'),
        ),
    ]
